Repository hitch-2011/hitch-fe, pull requests merged in 2021-05, with the labels that each got.

#12 Feature/form styles
  package-lock.json
  package.json
  public/index.html
  src/assets/fonts/futura-bold-03-webfont.woff
  src/assets/fonts/futura-bold-03-webfont.woff2
  src/assets/fonts/futura-medium-01-webfont.woff
  src/assets/fonts/futura-medium-01-webfont.woff2
  src/assets/fonts/futura-mediumitalic-02-webfont.woff
  src/assets/fonts/futura-mediumitalic-02-webfont.woff2
  src/components/App/App.css
  src/components/App/App.scss
  src/components/App/App.tsx
  src/components/Form/Form.scss
  src/components/Form/Form.tsx
  src/index.css
  src/index.scss
  src/index.tsx
  src/styles/_animations.scss
  src/styles/_base.scss
  src/styles/_fonts.scss
  src/styles/_variables.scss
Labels: Front End

#22 Feature/form restructure
  src/components/App/App.tsx
  src/components/App/_App.scss
  src/components/DaysAndTime/DaysAndTime.tsx
  src/components/DaysAndTime/_DaysAndTimes.scss
  src/components/Form/Form.tsx
  src/components/Form/_Form.scss
  src/components/LandingPage/LandingPage.scss
  src/components/LandingPage/LandingPage.tsx
  src/components/LandingPage/_LandingPage.scss
  src/components/Registration/Registration.tsx
  src/components/Registration/_Registration.scss
  src/index.scss
  src/interfaces/interfaces.tsx
  src/styles/_base.scss
  src/styles/_variables.scss
Labels: Front End, Pull Request

#24 Feature/input testing
  cypress/integration/hitch-login_spec.js
  package-lock.json
  src/components/Form/Form.tsx
Labels: Front End, Testing

#31 Feature/side navigation
  cypress/integration/hitch-login_spec.js
  cypress/integration/hitch-menu_spec.js
  package-lock.json
  package.json
  src/assets/landing-logo.svg
  src/components/App/App.tsx
  src/components/App/_App.scss
  src/components/DaysAndTime/_DaysAndTimes.scss
  src/components/Form/_Form.scss
  src/components/LandingPage/LandingPage.tsx
  src/components/LandingPage/_LandingPage.scss
  src/components/Menu/Menu.tsx
  src/components/Menu/_Menu.scss
  src/components/Registration/Registration.tsx
  src/components/Registration/_Registration.scss
  src/index.scss
  src/index.tsx
  src/interfaces/interfaces.tsx
  src/styles/_animations.scss
  src/styles/_base.scss
  src/styles/_mixins.scss
Labels: Front End, Pull Request

#34 Feature/css adjustments
  cypress/integration/hitch-login_spec.js
  cypress/integration/hitch-menu_spec.js
  src/assets/images/landing-logo.svg
  src/components/App/App.tsx
  src/components/App/_App.scss
  src/components/DetailedRoute/DetailedRoute.tsx
  src/components/DetailedRoute/_DetailedRoute.scss
  src/components/Header/Header.tsx
  src/components/Header/_Header.scss
  src/components/LandingPage/LandingPage.tsx
  src/components/LandingPage/_LandingPage.scss
  src/components/MatchedRoutes/MatchedRoutes.tsx
  src/components/MatchedRoutes/_MatchedRoutes.scss
  src/components/Menu/Menu.tsx
  src/components/Menu/_Menu.scss
  src/components/Registration/Registration.tsx
  src/components/Registration/_Registration.scss
  src/index.scss
  src/interfaces/interfaces.tsx
Labels: Front End, Pull Request

#35 Feature/google places
  .gitignore
  cypress/integration/hitch-login_spec.js
  cypress/integration/hitch-menu_spec.js
  package-lock.json
  package.json
  src/components/App/App.tsx
  src/components/Header/_Header.scss
  src/components/OriginDestination/OriginDestination.tsx
  src/components/OriginDestination/_OriginDestination.scss
  src/components/PlacesInput/PlacesInput.tsx
  src/components/PlacesInput/_PlacesInput.scss
  src/components/Registration/Registration.tsx
  src/index.scss
Labels: Front End

#37 Feature/connect to backend
  cypress/integration/hitch-login_spec.js
  cypress/integration/hitch-menu_spec.js
  cypress/videos/hitch-login_spec.js.mp4
  cypress/videos/hitch-menu_spec.js.mp4
  package-lock.json
  src/apiCalls.ts
  src/components/App/App.tsx
  src/components/DetailedRoute/DetailedRoute.tsx
  src/components/MatchedRoutes/MatchedRoutes.tsx
  src/components/Registration/Registration.tsx
  src/interfaces/interfaces.tsx
Labels: Front End, Pull Request, enhancement

#41 Feature/pwa setup
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/index.tsx
Labels: Front End, Pull Request, enhancement

#42 Change start_url to https
  public/favicon.ico
  public/index.html
  public/manifest.json
Labels: Front End, Pull Request

#45 Feature/link matched rides
  cypress/integration/hitch-menu_spec.js
  src/components/Days/Days.scss
  src/components/DetailedRoute/DetailedRoute.tsx
  src/components/Header/_Header.scss
  src/components/MatchedRoutes/MatchedRoutes.tsx
  src/components/MatchedRoutes/_MatchedRoutes.scss
Labels: Front End, enhancement
